### ISSUE TITLE
Data Question

### ISSUE THREAD

**Issue by justinelliotmeyers** [etalab/cadastre.data.gouv.fr#92]
Hello!
I am trying to better understand the data here: https://cadastre.data.gouv.fr/datasets/cadastre-etalab
I would like to map every village/ settlement/ city in Guadeloupe. I downloaded the data here: https://cadastre.data.gouv.fr/data/etalab-cadastre/2020-10-01/shp/departements/971/
I believe the cadastre-971-lieux_dits-shp.zip is places I am looking for. The attributes in the data seem a bit chaotic. 
Do you have metadata about these datasets explaining what they are? And is there a cleaned version of this data with better attributes?
Thank you for your time and help,
Justin

**Comment by ThomasG77** [comment]
Hi,

> I would like to map every village/ settlement/ city in Guadeloupe

For city and village, you have the info in file [cadastre-971-communes-shp.zip](https://cadastre.data.gouv.fr/data/etalab-cadastre/2020-10-01/shp/departements/971/cadastre-971-communes-shp.zip) Settlement are more or less the "lieu dit", a place within the city, village that do not have adresses where some houses aggregates.

Concerning SHP `cadastre-971-lieux_dits-shp.zip` is resulting from a GeoJSON that has been generated from a French old standard called EDIGEO. For what we call "lieux dits", the original structure contains only textual name, sometimes split among different columns due to length called `TEX`, `TEX2`, `TEX3`, `TEX4`, `TEX5`, `TEX6`, `TEX7`, `TEX8`, `TEX9`, `TEX10`. We joined them with https://github.com/etalab/cadastre/blob/master/lib/convert/pci.js#L142-L144

For metadata reference from the original EDIGEO format before any transformation, you can refer to https://www.collectivites-locales.gouv.fr/sites/default/files/migration/standard_edigeo_2013.pdf#page=50 and https://www.collectivites-locales.gouv.fr/sites/default/files/migration/standard_edigeo_2013.pdf#page=79 (document in French)

Another approach can be to use the file "cadastre-971-batiments-shp.zip" to grasp where people really lives not based on named places but on building (batiments is the French word for building)

You can also take a look at this file ftp://BDTOPO_V3_ext:Aish3ho8!!!@ftp3.ign.fr/BDTOPO_3-0_2021-12-15/BDTOPO_3-0_TOUSTHEMES_GPKG_RGAF09UTM20_D971_2021-12-15.7z for Guadeloupe. URL is an excerpt from BD Topo (more or less an equivalent of the OS MasterMap product) URL https://geoservices.ign.fr/bdtopo#telechargementgpkgdep
Doing an `ogrinfo` on the gpkg file could help you grasp the overall layers availability. Otherwise look at the big documentation https://geoservices.ign.fr/documentation/donnees/vecteur/bdtopo

**Comment by justinelliotmeyers** [comment]
Appreciate the insight! Also currently working on New Caledonia. Which is quite a bit different!
main gis data: https://georep-dtsi-sgt.opendata.arcgis.com/ - license update coming sometime this year to align with Licence Ouverte 2.0

census data - I need for villages if possible. Not seeing it in any of these:
https://www.insee.fr/fr/statistiques/2122859
https://www.isee.nc/
https://sdd.spc.int/news/2021/12/01/popgis-NC-now-available

Any insight into this?

and are there addresses for NC anywhere/ buildings?

Really appreciate all of your help!

**Comment by ThomasG77** [comment]
Look at https://github.com/etalab/api-geo/issues/135#issue-1074211190
The exact link could be found at https://www.isee.nc/population/recensement then click on link "[Consulter les chiffres des populations légales](https://www.isee.nc/component/phocadownload/category/195-donnees?download=768:la-population-legale)"
For easy consumption, I've also compiled the info at https://github.com/etalab/decoupage-administratif/blob/master/sources/collectivites-outremer.csv (not geographic part but at least for attributes)

Closing the issue as now discussion unrelated. Will answer other question here but need to clean the issues of the repo. Can't keep them sleeping ;)

**Comment by justinelliotmeyers** [comment]
Thank you!

**Comment by ThomasG77** [comment]
Found the geographic part at https://www.arcgis.com/home/item.html?id=bc8f0eec7d614853b0e9d1a9bd9649ef (a zip containing a GeoDatabase)
